import Head from "next/head";
import Script from "next/script";
import { unwrapCookies } from "../common/unwrapCookies";
import styles from "../styles/Home.module.css";

export function getServerSideProps({ req: { cookies } }) {
  const experiments = unwrapCookies(cookies);

  return {
    props: {
      experiments,
    },
  };
}

export default function Home({ experiments }) {
  useEffect(() => {
    console.log("exp", experiments);
  }, [experiments]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        id="gtag-exp"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            ${experiments.map(({ id, variant }) => {
              return `gtag('set', {'experiments': [{'id': '${id}', 'variant': '${variant}'}]});`;
            })}

            gtag('config', 'UA-129018078-2');
          `,
        }}
      />

      <main className={styles.main}>Homepage</main>
    </div>
  );
}
